name: Daily Auto Run

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - developer
  pull_request:
    branches:
      - developer
  workflow_dispatch:

jobs:
  run-auto-script:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run daily scraper
        run: python auto_run.py
